<?xml version="1.0"?>

<!DOCTYPE dictionary  [
<!ELEMENT dictionary (entry+)>
	<!ELEMENT entry (key1, key2, value+)>
		<!ELEMENT key1 (#PCDATA)>
		<!ELEMENT key2 (#PCDATA)>
		<!ELEMENT value (attrinfo1,attrinfo2)>
			<!ELEMENT attrinfo1 (#PCDATA)>
			<!ELEMENT attrinfo2 (#PCDATA)>
]>

<dictionary>


<!--  ***** BBBB *****
        setB.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
	setB.add("CATGPENREL.CATENTRY_ID = STORECENT.CATENTRY_ID");
 -->

  <entry>
      <key1>CATGRPDESC</key1>
      <key2>STORECENT</key2>
      <value>
	  <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>StoreCEntIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** CCCC *****
        setC.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
	setC.add("CATGPENREL.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->

  <entry>
      <key1>CATGRPDESC</key1>
      <key2>CATENTRY</key2>
      <value>
	  <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** DDDD *****
        setD.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
	setD.add("CATGPENREL.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
 -->
  <entry>
      <key1>CATGRPDESC</key1>
      <key2>CATENTDESC</key2>
      <value>
	  <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** EEEE *****
        setD.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
 -->
  <entry>
      <key1>CATGRPDESC</key1>
      <key2>CATGPENREL</key2>
      <value>
	  <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** FFFF *****
        setF.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
	setF.add("CATGPENREL.CATENTRY_ID = CATENTRY.CATENTRY_ID");
	setF.add("LISTPRICE.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->
  <entry>
      <key1>CATGRPDESC</key1>
      <key2>LISTPRICE</key2>
      <value>
	  <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>ListPriceCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** GGGG *****
        setG.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
	setG.add("CATGPENREL.CATENTRY_ID = CATENTRY.CATENTRY_ID");
	setG.add("INVSTVW.ITEMSPC_ID = CATENTRY.ITEMSPC_ID");
 -->

  <entry>
      <key1>CATGRPDESC</key1>
      <key2>INVSTVW</key2>
      <value>
	  <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>InvStVwItemSpcIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryItemSpcIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>




<!--  ***** HHHH *****
        setH.add("CATENTRY.CATENTRY_ID = STORECENT.CATENTRY_ID");
 -->

  <entry>
      <key1>CATENTRY</key1>
      <key2>STORECENT</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>StoreCEntIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** IIII *****
        setI.add("CATENTRY.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
 -->
  <entry>
      <key1>CATENTRY</key1>
      <key2>CATENTDESC</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** JJJJ *****
        setJ.add("CATENTRY.CATENTRY_ID = CATGPENREL.CATENTRY_ID");
 -->
  <entry>
      <key1>CATENTRY</key1>
      <key2>CATGPENREL</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** KKKK *****
	setK.add("LISTPRICE.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->
  <entry>
      <key1>CATENTRY</key1>
      <key2>LISTPRICE</key2>
      <value>
	  <attrinfo1>ListPriceCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** LLLL *****
	setL.add("INVSTVW.ITEMSPC_ID = CATENTRY.ITEMSPC_ID");
 -->

  <entry>
      <key1>CATENTRY</key1>
      <key2>INVSTVW</key2>
      <value>
	  <attrinfo1>InvStVwItemSpcIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryItemSpcIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>




<!--  ***** MMMM *****
	setM.add("CATENTRY.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
        setM.add("CATENTRY.CATENTRY_ID = STORECENT.CATENTRY_ID");
 -->

  <entry>
      <key1>CATENTDESC</key1>
      <key2>STORECENT</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>StoreCEntIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** NNNN *****
	setN.add("CATENTRY.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
        setN.add("CATENTRY.CATENTRY_ID = CATGPENREL.CATENTRY_ID");
 -->
  <entry>
      <key1>CATENTDESC</key1>
      <key2>CATGPENREL</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** OOOO *****
	setO.add("CATENTRY.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
	setO.add("LISTPRICE.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->
  <entry>
      <key1>CATENTDESC</key1>
      <key2>LISTPRICE</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>ListPriceCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>


<!--  ***** PPPP *****
	setP.add("CATENTRY.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
	setP.add("INVSTVW.ITEMSPC_ID = CATENTRY.ITEMSPC_ID");
 -->

  <entry>
      <key1>CATENTDESC</key1>
      <key2>INVSTVW</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>InvStVwItemSpcIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntryItemSpcIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** QQQQ *****
	setQ.add("CATENTREL.CATENTRY_ID_PARENT = ATTRIBUTE.CATENTRY_ID");
 -->

  <entry>
      <key1>ATTRIBUTE</key1>
      <key2>CATENTREL</key2>
      <value>
	  <attrinfo1>AttributeCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntRelParentIdentifierAttributeInfo</attrinfo2>
      </value>
  </entry>

<!--  ***** RRRR *****
	setR.add("CATENTREL.CATENTRY_ID_CHILD = ATTRVALUE.CATENTRY_ID");
 -->

  <entry>
      <key1>ATTRVALUE</key1>
      <key2>CATENTREL</key2>
      <value>
	  <attrinfo1>AttrValueCatEntIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>CatEntRelChildIdentifierAttributeInfo</attrinfo2>
      </value>
  </entry>

<!--  ***** SSSS *****
	setS.add("ATTRIBUTE.ATTRIBUTE_ID = ATTRVALUE.ATTRIBUTE_ID");
 -->

  <entry>
      <key1>ATTRVALUE</key1>
      <key2>ATTRIBUTE</key2>
      <value>
	  <attrinfo1>AttrValueAttributeIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>AttributeAttributeIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>AttrValueLanguageIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>AttributeLanguageIdentifierAttributeInfo</attrinfo2>
      </value>
  </entry>

<!--  ***** TTTT *****
	setT.add("CATENTRY.CATENTRY_ID = ATTRVALUE.CATENTRY_ID");
 -->

  <entry>
      <key1>ATTRVALUE</key1>
      <key2>CATENTRY</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>AttrValueCatEntIdentifierAttributeInfo</attrinfo2>
      </value>
  </entry>

<!--  ***** UUUU *****
        setU.add("CATENTRY.CATENTRY_ID = PRSETCEREL.CATENTRY_ID");
 -->
  <entry>
      <key1>CATENTRY</key1>
      <key2>PRSETCEREL</key2>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>PrsetcerelCatEntIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry> 

<!--  ***** VVVV *****
        setV.add("OFFER.OFFER_ID = OFFERPRICE.OFFER_ID");
        setV.add("TRADEPOSCN.TRADEPOSCN_ID = OFFER.TRADEPOSCN_ID");
 -->
  <entry>
      <key1>OFFERPRICE</key1>
      <key2>TRADEPOSCN</key2>
      <value>
	  <attrinfo1>OfferOfferIdAttributeInfo</attrinfo1>
	  <attrinfo2>OfferPriceOfferIdAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>OfferTradeposcnIdAttributeInfo</attrinfo1>
	  <attrinfo2>TradeposcnTradeposcnIdAttributeInfo</attrinfo2>
      </value>
 </entry> 

<!--  ***** WWWW *****
        setW.add("OFFER.CATENTRY_ID = CATENTRY.CATENTRY_ID");
        setW.add("OFFER.OFFER_ID = OFFERPRICE.OFFER_ID");
 -->
  <entry>
      <key1>OFFERPRICE</key1>
      <key2>CATENTRY</key2>
      <value>
	  <attrinfo1>OfferOfferIdAttributeInfo</attrinfo1>
	  <attrinfo2>OfferPriceOfferIdAttributeInfo</attrinfo2>
      </value>
      <value>
	  <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
	  <attrinfo2>OfferCatentryIdAttributeInfo</attrinfo2>
      </value>
 </entry> 

  <!--  ***** XXXX *****
        setG.add("CATGPENREL.CATGROUP_ID = CATGRPDESC.CATGROUP_ID");
       setG.add("CATGPENREL.CATENTRY_ID = CATENTRY.CATENTRY_ID");
       setG.add("STOREINV.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->

  <entry>
      <key1>CATGRPDESC</key1>
      <key2>STOREINV</key2>
      <value>
         <attrinfo1>CatGpEnRelCatGpIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatGrpDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
         <attrinfo1>CatGpEnRelCatEntIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
         <attrinfo1>StoreInvCatEntIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("STOREINV.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->

  <entry>
      <key1>CATENTRY</key1>
      <key2>STOREINV</key2>
      <value>
         <attrinfo1>StoreInvCatEntIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("CATENTRY.CATENTRY_ID = CATENTDESC.CATENTRY_ID");
       setG.add("STOREINV.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->

  <entry>
      <key1>CATENTDESC</key1>
      <key2>STOREINV</key2>
      <value>
         <attrinfo1>CatEntryIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatEntDescIdentifierAttributeInfo</attrinfo2>
      </value>
      <value>
         <attrinfo1>StoreInvCatEntIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("CATGRPDESC.CATGROUP_ID = STORECGRP.CATGROUP_ID");
 -->

  <entry>
      <key1>CATGRPDESC</key1>
      <key2>STORECGRP</key2>
      <value>
         <attrinfo1>CatGrpDescIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>StoreCGrpCatGroupIdAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("CATGRPDESC.CATGROUP_ID = CATGROUP.CATGROUP_ID");
 -->

  <entry>
      <key1>CATGRPDESC</key1>
      <key2>CATGROUP</key2>
      <value>
         <attrinfo1>CatGrpDescIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>CatGroupIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("CATGROUP.CATGROUP_ID = STORECGRP.CATGROUP_ID");
 -->

  <entry>
      <key1>CATGROUP</key1>
      <key2>STORECGRP</key2>
      <value>
         <attrinfo1>CatGroupIdentifierAttributeInfo</attrinfo1>
         <attrinfo2>StoreCGrpCatGroupIdAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("STDPRICEVW.CATENTRY_ID = CATENTRY.CATENTRY_ID");
 -->

  <entry>
      <key1>STDPRICEVW</key1>
      <key2>CATENTRY</key2>
      <value>
         <attrinfo1>StdPriceVwCatentryIdAttributeInfo</attrinfo1>
         <attrinfo2>CatEntryIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("CATTOGRP.CATGROUP_ID = CATGROUP.CATGROUP_ID");
 -->

  <entry>
      <key1>CATTOGRP</key1>
      <key2>CATGROUP</key2>
      <value>
         <attrinfo1>CattoGrpCatGroupIdAttributeInfo</attrinfo1>
         <attrinfo2>CatGroupIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>

<!--  ***** XXXX *****
       setG.add("CATTOGRP.CATALOG_ID = CATALOG.CATALOG_ID");
 -->

  <entry>
      <key1>CATTOGRP</key1>
      <key2>CATALOG</key2>
      <value>
         <attrinfo1>CattoGrpCatalogIdAttributeInfo</attrinfo1>
         <attrinfo2>CatalogIdentifierAttributeInfo</attrinfo2>
      </value>
 </entry>
</dictionary>
